### ISSUE TITLE
Adding Open in Colab Badge

### ISSUE THREAD

**Issue by amrrs** [Rajsoni03/Neural-Plot#7]
If you could add Open in Colab badge, It'd help a lot for those who want to try this out!

**Comment by Rajsoni03** [comment]
Thanks for your feedback.
I have updated the "Open in collab" badge.

**Comment by amrrs** [comment]
Thanks!

**Comment by Rajsoni03** [comment]
I have also published it on PyPi.
[https://pypi.org/project/neuralplot/](https://pypi.org/project/neuralplot/)

**Comment by amrrs** [comment]
Congratulations!
